### PR TITLE
Updated version strings to 1.8.1-alpha tag.

### PR DESCRIPTION
**Pull request by rkofman**
Since there's a tagged release, I figured it's necessary to update the version strings to make sure developers that are riding the alpha wave aren't confused (if they use the built files, their teammates would think they're using 1.7.1 -- causing all sorts of havoc and debugging hell).

Not sure how to request that this change get pulled into the 1.8.1-alpha tag, but that's certainly part of the intent.

### CODE REVIEW

**Comment by rkofman** [comment]
Closing, will re-open against the "development" branch.

**Comment by robinfhu** [comment]
Yes, against dev plz

**Comment by robinfhu** [comment]
Yeah sorry, I forgot to do this.

**Comment by rkofman** [comment]
Unfortunately, I seem to be failing to generate the correct diff: when doing `grunt release`, off the 1.8.1-alpha tag, the diff in the minimized js and css files seems to be more than just the version string comment.

Would you mind just doing it for me?

**Comment by robinfhu** [comment]
Yep, looking at it now.

**Comment by robinfhu** [comment]
This is done. The release tag was force moved to the newer version.

**Comment by rkofman** [comment]
thanks!

**Pull request closed without merging**
