### PR TITLE
Add support for line chart to place legend on bottom

### PR DESCRIPTION
**Pull request by slavede**

### CODE REVIEW

**Comment by liquidpele** [comment]
Looks good!  Thanks for contributing!

**Comment by slavede** [comment]
Glad to help, any idea when this will be tagged in some of the following versions?

**Comment by liquidpele** [comment]
I built latest and pushed it up, so it's in the 1.8.2-dev version now.

**Comment by slavede** [comment]
What about official version (not -dev)? Because I need that one for my build system...

**Comment by liquidpele** [comment]
will probably be a while before another version comes out, we don't do it for every PR.

**Comment by slavede** [comment]
Of course, no problem, it's not so urgent, it was just matter of finding out rough number, a week, a month, 2-3 months?

**Comment by liquidpele** [comment]
Few months probably.

**Pull request merged**
