### PR TITLE
Pie title supports resizing.

### PR DESCRIPTION
**Pull request by mgalloue**
Adjust automatically the font-size of the title, with respect to the current donut chart size.

- It's not necessary to define a size in a css.
- It supports resizing.
- it depends on the title length
- it takes into account the donut ratio.

### CODE REVIEW

**Comment by robinfhu** [comment]
Will look at this in about an hour.

**Comment by robinfhu** [comment]
Thanks!

**Comment by mikyladewitt** [comment]
Hello,

How do we use this? This feature is perfect for a problem I am trying to solve, but I don't see how to turn it on.

Thanks!

**Comment by liquidpele** [comment]
If you just want to resize the inner text, you can modify the CSS, ala the class name on it:  .nv-pie-title

**Comment by mikyladewitt** [comment]
@liquidpele ah I may have misunderstood which title this was referring to. I was looking for a built in way to modify the chart title, which I just realized is actually angular-nvd3 specific. Sorry for the confusion!

**Pull request merged**
