### PR TITLE
Not to adjust top margin if it was specified.

### LINKED ISSUE #1585: Some chart: Set top margin is not working
I try to set top margin for some chart, but it's not working (it work fine with right, bottom, left exclude top margin). Please check link demo below:

[https://jsfiddle.net/thienhv295/wouy3qLx/](https://jsfiddle.net/thienhv295/wouy3qLx/)

Thank you.

### PR DESCRIPTION
**Pull request by ovvn**
Fixes #1585 and #1764.

### CODE REVIEW

**Comment by liquidpele** [comment]
Hmm... one of the failed tests is " ✗ translates nv-wrap after legend height calculated"

That sounds like possibly related?

**Comment by ovvn** [comment]
Fixed tests, not sure why it gets "after each" hook on travis, locally all tests passed.

**Comment by liquidpele** [comment]
awesome, thanks!

**Comment by liquidpele** [comment]
Yea, travis has been totally unstable for a while for us.

**Pull request merged**
