### PR TITLE
Support for error bars in MultiBarChart

### PR DESCRIPTION
**Pull request by lomereiter**
Also added the 'errorBarColor' option to both MultiBarChart and MultiBarHorizontalChart

### CODE REVIEW

**Comment by robinfhu** [comment]
You have an update to the example file so we can see what this looks like?

**Comment by lomereiter** [comment]
Added an example. The usage and appearance are basically the same as in MultiBarHorizontal.

**Comment by robinfhu** [comment]
Looks okay. There's a bar that seems to have one of the error markers cut off.  It's possible this is due to the yScale not taking into account the maximum value it can have in the domain.
multibar with errors

**Comment by lomereiter** [comment]
OK, thanks for the input. I also see that transitions are not applied to the chart after my changes. Don't merge until I'll fix these.

**Comment by liquidpele** [comment]
@lomereiter I went ahead and merged this, but I did notice that the initial transition makes the bars fly over from the left instead of just growing up from the position they should already be at....   can you take a look at fix that?   I made an issue for it here:   https://github.com/novus/nvd3/issues/1076

**Pull request merged**
