### PR TITLE
bugfix - donut outside labels should follow the start - end angles

### PR DESCRIPTION
**Pull request by Ghingis**
problem: http://plnkr.co/edit/EGjzqa?p=preview

### CODE REVIEW

**Comment by robinfhu** [comment]
Your example also uses angular-nvd3, which is not something we are officially involved with. Closing as 'can't reproduce'.

**Comment by Ghingis** [comment]
angular-nvd3 is just a plain wrapper for angular...
Any way I updated the plunker it's bare nvd3 now if I am right, please check that out

**Comment by robinfhu** [comment]
@Ghingis sorry, but I am looking at your plnkr, and I don't understand what is actually wrong with the chart.  Please explain what is broken.

**Comment by Ghingis** [comment]
@robinfhu probably my second link miss lead you (that is the fixed one)
Basically the outer label dose not follow the start and end angle of the donut, so it always shows up like it was a full donut when it's not the case.

half donut with misplaced label: http://plnkr.co/edit/EGjzqa?p=preview
full donut for reference: http://plnkr.co/edit/ZNsXIN?p=preview
half donut with fixed label: http://plnkr.co/edit/TKjbco?p=preview

Also I made a beautiful image (with paint :)), I hope it's helps me illustrate even more: 
http://prntscr.com/62z11e

Thanks

**Comment by liquidpele** [comment]
Yup, it looks like when donutLabelsOutside is true is when it happens, interesting.

**Comment by liquidpele** [comment]
Oh, you're trying to merge into master.   New changes need to go into the development branch.  Please change the pull request to go there, thanks!

**Comment by robinfhu** [comment]
thanks @Ghingis I understand now.  Yeah this is a bug then.

**Comment by liquidpele** [comment]
Also make sure you check out the latest code, a lot changed and it looks like github is saying it can't auto-merge even this small change!

**Comment by robinfhu** [comment]
We merged in the updated PR. Closing this one.

**Pull request closed without merging**
