### PR TITLE
change AreaPath for confidence interval

### PR DESCRIPTION
**Pull request by gepuro**

### CODE REVIEW

**Comment by liquidpele** [comment]
Can you give a description or some screenshots of what this is doing/fixing?

**Comment by gepuro** [comment]
I want to draw confidence interval for time series analysis (e.g. forecasting used by arima model)
Screenshot is here. https://www.dropbox.com/s/u0yueaed89coi4p/Screenshot%20from%202015-05-12%2008%3A50%3A04.png?dl=0

and Sample code is as follows:

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link href="../build/nv.d3.css" rel="stylesheet" type="text/css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.2/d3.min.js" charset="utf-8"></script>
    <script src="../build/nv.d3.js"></script>
    <script src="lib/stream_layers.js"></script>

    <style>
        text {
            font: 12px sans-serif;
        }
        svg {
            display: block;
        }
        html, body, #chart, svg {
            margin: 0px;
            padding: 0px;
            height: 100%;
            width: 100%;
        }
    </style>
</head>
<body>


     <div id="linewithfocuschart"><svg style="width:700px;height:400px;"></svg></div>


    <script>


    
        data_linewithfocuschart=[{"color": "blue", "values": [{"y": 27.3, "x": 1426086000000}, {"y": 25.7, "x": 1426172400000}, {"y": 24.1, "x": 1426258800000}, {"y": 26.9, "x": 1426345200000}, {"y": 29.9, "x": 1426431600000}, {"y": 27.9, "x": 1426518000000}, {"y": 27.0, "x": 1426604400000}, {"y": 26.6, "x": 1426690800000}, {"y": 24.9, "x": 1426777200000}, {"y": 22.1, "x": 1426863600000}, {"y": 24.9, "x": 1426950000000}, {"y": 27.4, "x": 1427036400000}, {"y": 26.8, "x": 1427122800000}, {"y": 25.7, "x": 1427209200000}, {"y": 24.9, "x": 1427295600000}, {"y": 23.5, "x": 1427382000000}, {"y": 21.7, "x": 1427468400000}, {"y": 25.5, "x": 1427554800000}, {"y": 26.6, "x": 1427641200000}, {"y": 27.0, "x": 1427727600000}, {"y": 27.6, "x": 1427814000000}], "key": "act", "yAxis": "1"}, {"color": "red", "area": 1, "values": [{"yupper": 29.8, "y": 27.1, "ylower": 24.5, "x": 1427932800000}, {"yupper": 29.3, "y": 25.4, "ylower": 21.4, "x": 1428019200000}, {"yupper": 28.3, "y": 23.3, "ylower": 18.4, "x": 1428105600000}, {"yupper": 32.5, "y": 26.7, "ylower": 21.0, "x": 1428192000000}, {"yupper": 35.8, "y": 28.7, "ylower": 22.3, "x": 1428278400000}, {"yupper": 35.2, "y": 28.2, "ylower": 21.2, "x": 1428364800000}, {"yupper": 35.4, "y": 27.9, "ylower": 20.4, "x": 1428451200000}, {"yupper": 35.6, "y": 27.1, "ylower": 18.5, "x": 1428537600000}], "key": "forecast", "yAxis": "1"}];

    nv.addGraph(function() {
        var chart = nv.models.lineWithFocusChart();

        chart.margin({top: 30, right: 50, bottom: 20, left: 100});
        chart.yDomain([10, 40]);

        var datum = data_linewithfocuschart;

        chart.color(d3.scale.category20c().range());



            chart.x2Axis
                .tickFormat(function(d) { return d3.time.format('%d %b %Y')(new Date(parseInt(d))) }
);
            chart.y2Axis
                .tickFormat(d3.format(',.2f'));
            chart.xAxis
                .tickFormat(function(d) { return d3.time.format('%d %b %Y')(new Date(parseInt(d))) }
);
            chart.yAxis
                .tickFormat(d3.format(',.2f'));

                chart.tooltipContent(function(key, y, e, graph) {
                    var x = d3.time.format("%d %b %Y")(new Date(parseInt(graph.point.x)));
                    var y = String(graph.point.y);
                    var y = String(graph.point.y);

                    tooltip_str = '<center><b>'+key+'</b></center>' + y + ' on ' + x;
                    return tooltip_str;
                });

      chart.showLegend(true);



        


        d3.select('#linewithfocuschart svg')
            .datum(datum)
            .transition().duration(500)
            .attr('width', 700)
            .attr('height', 400)
            .call(chart);


    });




    </script>

</body>
</html>
```

**Comment by liquidpele** [comment]
His example image: 

example

**Comment by liquidpele** [comment]
This seems like a conflicting item with https://github.com/novus/nvd3/pull/312, though this one gives more capability I think and the other one is stale...   

however, I just noticed you made this PR for master.  All pull requests should be to the development branch since that's the latest code.  Please re-submit as a pull request to development. 

https://github.com/novus/nvd3#a-few-rules-for-pull-requests

**Comment by liquidpele** [comment]
@joshjordan @robinfhu do ya'll care if I move all main dev to master before 1.8.1?  The PR to master thing has been way too frequent of an issue...

**Comment by robinfhu** [comment]
@liquidpele I think it's fine.

**Comment by gepuro** [comment]
Thank you for your comment.
I re-submit here (https://github.com/novus/nvd3/pull/1032).

**Pull request closed without merging**
