### PR TITLE
modify indexify to divide by v and not by v+1

### PR DESCRIPTION
**Pull request by bernhard-42**
The cumulativeChart is actually an index chart, see [http://mbostock.github.io/protovis/ex/index-chart.html](http://mbostock.github.io/protovis/ex/index-chart.html) (I think, the name should be changed some day).

However, the first thing should be to correct the math: the `y` axis shows the percentage of `y_i` relative to the index value `v`. So the right formula is `(y_i - v)/v` (as also used in Mike Bostocks code) and not `(y_i - v)/(1 + v)`

### CODE REVIEW

**Comment by bernhard-42** [comment]
Travis failed with
     The command "npm install -g grunt-cli" failed and exited with 1 during .
which is not related to the changes ...

**Comment by liquidpele** [comment]
Looks correct to me...  thanks for contributing!

**Comment by bernhard-42** [comment]
I just saw that there is another piece of code above that has the same strange logic.
Sorry, missed that before

cumulativeLineChart.js line 175

```
if (initialDomain[0] < -.95) initialDomain[0] = -.95;

return [
        (initialDomain[0] - initialDomain[1]) / (1 + initialDomain[1]),
        (initialDomain[1] - initialDomain[0]) / (1 + initialDomain[0])
];
```

I don’t know what happens there. Why is the value changed instead of making the line disabled?
And why only initialDomain[0]? And how can this happen after the filter?

If the above logic is OK (and this currently beyond my understanding), then it needs to changed to something like:

```
if (Math.abs(initialDomain[0]) < 0.00001) { 
    initialDomain[0] = (initialDomain[0] < 0) ? -0.00001 : 0.00001; 
}
return [
        (initialDomain[0] - initialDomain[1]) / initialDomain[1],
        (initialDomain[1] - initialDomain[0]) / initialDomain[0]
];
```

However I'd prefer to understand that part of the code better before issuing a PR.

Do you know what happens in (!rescaleY) case?

**Comment by liquidpele** [comment]
tbh I've barely messed with cumulative line chart because I never had the need to use it... so your guess is as good as mine :)

**Comment by bernhard-42** [comment]
I'll have a look at it and try to understand it. Will then come up with a PR that makes sense for review

**Comment by bernhard-42** [comment]
I analyzed the behavior and created a pull request https://github.com/novus/nvd3/pull/2014
Hope this works now.

**Pull request merged**
