### PR TITLE
Add legendRightAxisHint for multiChart

### PR DESCRIPTION
**Pull request by dbabaioff**

### CODE REVIEW

**Comment by liquidpele** [comment]
Please also document the option in documentation.html

**Comment by dbabaioff** [comment]
It's there: https://github.com/novus/nvd3/blob/master/examples/documentation.html#L750
I need to include in other places?

**Comment by liquidpele** [comment]
Oh cool, nevermind!

**Comment by liquidpele** [comment]
Thanks for contributing!

**Comment by dbabaioff** [comment]
:+1:

**Pull request merged**
