### PR TITLE
Add fontSize option for axis labels

### PR DESCRIPTION
**Pull request by mikeyoon**
Simple font-size override option for axis labels. I think in the future it could also allow a function override for more responsive behavior.

### CODE REVIEW

**Comment by liquidpele** [comment]
This seems like something better handled with CSS.

**Comment by mikeyoon** [comment]
I think CSS would solve the case where there are a limited set of font-sizes to choose from, but our situation involves the user picking from any number of font-sizes, or typing it in, kind of like formatting in excel or similar.

**Comment by liquidpele** [comment]
I guess this does make sense for axis..   please document the new option in documention.html then though.

**Comment by mikeyoon** [comment]
Thanks, does documentation go in the nvd3-community repo?

**Comment by liquidpele** [comment]
No, I just use that for the doc site...  long story ;)

**Pull request merged**
