### PR TITLE
Fix scatter window resize issue where it stops doing hover on the scatte...

### PR DESCRIPTION
**Pull request by liquidpele**
...rChart properly - https://github.com/novus/nvd3/issues/971

### CODE REVIEW

**Comment by liquidpele** [comment]
@robinfhu pls review :)

**Comment by robinfhu** [comment]
@liquidpele okay looking.  Sorry been a little busy lately.

**Comment by robinfhu** [comment]
Great thanks!

**Comment by robinfhu** [comment]
Out of curiosity, why did removing the nv-point-clips ID solve this issue?

**Comment by liquidpele** [comment]
it didn't I just made it a class name to be more technically correct in case multiple charts exist on the same page... what actually fixed it was removing the clippaths themselves but I'm honestly not sure why that worked...I suspect something with in d3 itself was losing track of the clippings

**Comment by robinfhu** [comment]
Cool thanks!

**Pull request merged**
