### PR TITLE
Make tooltips get the right values if people change the getX and getY getter functions.

### PR DESCRIPTION
**Pull request by liquidpele**
:p

### CODE REVIEW

**Comment by liquidpele** [comment]
Fixes part of https://github.com/novus/nvd3/issues/893 where the tooltip showed NaN

**Comment by robinfhu** [comment]
Oh right this is a big deal!

**Comment by liquidpele** [comment]
unit tests are passing, the last one failed just because travis CI bombed out completely ;)

**Comment by robinfhu** [comment]
Is this PR a work in progress, or is this everything that needs to be changed?

**Comment by liquidpele** [comment]
I think it is everything but please look and see if I overlooked anything

**Comment by robinfhu** [comment]
The important charts were addressed, it's fine. Thanks!

**Comment by RenatoUtsch** [comment]
Was any chart not addressed?

**Comment by liquidpele** [comment]
I intended to get em all so if I missed one let me know!

**Comment by RenatoUtsch** [comment]
For example, I don't see the files of the bullet and cumulativeLine charts changed... neither ohlc...

**Comment by liquidpele** [comment]
Some charts don't use x/y getters or inherit from other objects that do.  If you can break one in a jsfiddle let me know.

**Comment by RenatoUtsch** [comment]
Okay.

Thanks for the good work!

**Comment by RenatoUtsch** [comment]
I am still noticing problems with the nvd3-discrete-bar-chart when using timestamps as the x values.

**Pull request merged**
