### PR TITLE
Issue 771 Tooltip pending removal fix

### PR DESCRIPTION
**Pull request by robinfhu**
Issue #771 fix.
I brought back some code that was removed from nv.tooltip.cleanup()

### CODE REVIEW

**Comment by robinfhu** [comment]
@petersondrew @liquidpele please take a look.

**Comment by petersondrew** [comment]
The idea behind my changes, and the reason that code was the way it was, is because the interactive layer re-uses that container div. Setting the css class just makes it invisible. (I even added tests for it)

Could you try perhaps changing the classname that the interactive layer uses to nvtooltip-hidden or something perhaps? If the class is applied in the interactive layer, and the css changed, then you can add this removal code back in as it will only remove those with nvtooltip-pending-removal and not nvtooltip-hidden.

Thoughts?

**Comment by robinfhu** [comment]
@petersondrew let me take a look. Thanks.

**Comment by robinfhu** [comment]
@petersondrew I see this line of code:

           var hidden = document.querySelector("#" + id + ".nvtooltip-pending-removal");
            if (hidden)
                hidden.className = "nvtooltip " + (classes? classes: "xy-tooltip");

This confuses me.  I'm trying to understand what this does but I can't.

Right now with my code change the behavior is exactly what I want.

**Comment by liquidpele** [comment]
So wait, just glancing at this, it looks like it'll remove all tooltips, what if there are multiple graphs on the screen with tooltips being shown?

**Comment by liquidpele** [comment]
var hidden = document.querySelector("#" + id + ".nvtooltip-pending-removal");
        if (hidden)
            hidden.className = "nvtooltip " + (classes? classes: "xy-tooltip");

It's finding anything with the .nvtooltip-pending-removal class with ALSO has an id attribute with the value of the id variable.  Then if it finds at least one, it changes the class attribute to be "nvtooltip xy-tooltip".

**Comment by liquidpele** [comment]
Like I said in the defect, I think it might be better to just save the dom object outside the tooltip call function, and then when we need to find it again we can just do like tooltip_dom.node() and manipulate it as needed... that would remove all the unnecessary id and class selection stuff, and would make it so each chart had it's own encapsulated tooltip instead of them stepping over each other.

**Comment by robinfhu** [comment]
@liquidpele Oh, I see what you are saying.  I was basically copying old functionality, which behaved like I expected.  

Can @liquidpele  or @petersondrew PR a solution?

**Comment by liquidpele** [comment]
I'll try to look at it tonight

**Comment by robinfhu** [comment]
@liquidpele  thanks :+1: :-)

**Comment by liquidpele** [comment]
yea, so I looked at it last night, seems that nothing except the interactive guideline uses the tooltip object, everything else just uses a function to display the tooltip... so I'm giving this a little more thought, but I'm still working on it.

**Comment by robinfhu** [comment]
This is the last remaining issue I think we should solve. After this, we can release what's in development.

**Comment by liquidpele** [comment]
Just an update, I've got a chart using the tooltip object now instead of the "old" tooltips, just a few little style kinks to work out, but I've modified a lot so any other tooltip updates will likely just get overwritten by this.

**Comment by robinfhu** [comment]
SInce @liquidpele has taken over this, I am closing this PR.

**Comment by pimlinders** [comment]
@liquidpele it would be really nice if we could provide custom content when using "useInteractiveGuideline" as well. Note that on version 1.8.1 when "useInteractiveGuideline" is set to the true the guidelines remains on the last x axis position no matter the mouse position.

**Comment by liquidpele** [comment]
You can do chart.interactive guideline.tooltip.content generator()

Please open an issue for any bugs :)

**Comment by pimlinders** [comment]
@liquidpele you rock! Looked further into the mouse hover issue, seems to be something with d3 version 3.3.13. Updating d3 resolved the issue.

**Comment by liquidpele** [comment]
Oh yea, we require 3.4.4+ now due to some issues we saw with previous versions... the readme is only updated with that on the development branch and the 1.8.1alpha though :)

**Pull request closed without merging**
