### PR TITLE
Implements legendPosition (top and bottom) for stackedAreaChart

### PR DESCRIPTION
**Pull request by falbrech-hsdg**
Implements the legendPosition property with valid values "top" and "bottom" for the stackedAreaChart. The "controls", if shown, will always stay on top. (Could provide another property for their position)

Generation order of controls and legend had to be swapped for required legend position calculations.

### CODE REVIEW

**Comment by liquidpele** [comment]
This looks like it has conflicts with master... please sync with upstream.

**Comment by liquidpele** [comment]
Still appears to have conflicts...

**Comment by falbrech-hsdg** [comment]
@liquidpele Not "still", but "again" :-) 

Merging gets harder and harder with each feature / change merged in the meantime, so pleeease merge it soon, or re-implementing will be easier than the next merge.

**Comment by liquidpele** [comment]
Okay, looks good now thanks!

**Pull request merged**
