### PR TITLE
adding legendEnabled to tooltip default contentGenerator

### PR DESCRIPTION
**Pull request by bkjelden**
pretty simple change - adding an option to toggle the legend on/off on a tooltip, similar to the already existing option for tooltip headers.

### CODE REVIEW

**Comment by liquidpele** [comment]
This is already easily done with some CSS though... 

    .legend-color-guide { width: 1px; }
    .legend-color-guide > * {display: none}

**Comment by bkjelden** [comment]
Just curious - what's the reason for the headerEnabled option, then? It seems like that could also be easily hidden through css.

**Comment by liquidpele** [comment]
The pie charts don't utilize header since they have one less data point.

**Comment by bkjelden** [comment]
Makes sense. Thanks for clarifying.

**Pull request closed without merging**
