### PR TITLE
bugfix - donut outside labels should follow the start - end angles #647

### PR DESCRIPTION
**Pull request by Ghingis**
Related pull request: https://github.com/novus/nvd3/pull/647
But this one is from an up-to-date development branch.

### CODE REVIEW

**Comment by joshjordan** [comment]
@Ghingis can you write a test for this, please?

**Comment by Ghingis** [comment]
@joshjordan You mean a visual test like this, right?
https://github.com/Ghingis/nvd3/commit/7208045d0468cd465ccf0868e77373d837d91069

**Comment by robinfhu** [comment]
@Ghingis visual test is useful, so thanks for that.  Can you think of a way to write a test in the test/mocha folder for this?  Do you want advice on that?

**Comment by robinfhu** [comment]
I merged it and added some tests of my own

**Comment by Ghingis** [comment]
Thank you, I will check them

**Pull request merged**
