### PR TITLE
Bug fixes for multiBar model

### PR DESCRIPTION
**Pull request by ywplee**
- Removing duplicate declaration of 'parsed' 
- In stacked mode, clicking the lastly positioned serie's legend throws an error. It was trying to access the deleted reference. I added a null check.

### CODE REVIEW

**Comment by liquidpele** [comment]
Awesome, thanks!

**Comment by ywplee** [comment]
Np. By the way, do you guys have some type of lint task that I could run on
the source code? I noticed that there is jshint task registered in Grunt,
but wasn't sure if jshintrc is up to date or not.

**Comment by liquidpele** [comment]
It would be nice to add jshint to the build eventually, but it hasn't been done since it would be a lot of work to fix all the errors first...

**Comment by ywplee** [comment]
Got it. Moving forward, can I rely on the jshint rule you guys have specified for the repository to lint my code?

**Comment by liquidpele** [comment]
Never used whatever is configured there yet, so not sure... maybe @robinfhu has?

**Comment by robinfhu** [comment]
jshint was just never really used, I think because there were so many errors it would take a while to just fix them all.

**Pull request merged**
