### PR TITLE
Fixing Bug #945: Stacked Area "Expanded" view does not handle a point where all y values are 0

### PR DESCRIPTION
**Pull request by lucaslin**
Fixing Bug #945: Stacked Area "Expanded" view does not handle a point where all y values are 0

Making stackedArea (in Expanded view) display 0 (no area) at points where the total y value across all series is 0.

Note: style 'expand' and 'stack_percent' now are the same. One should probably be removed. (They seemed to be intended to produce the same thing)

Example: http://nvd3stackedarea.parseapp.com/

### CODE REVIEW

**Comment by liquidpele** [comment]
Looks like you make 'expand' and 'stack_percent' the same thing here...  I guess my question is, are they really the same thing?   It seems like they would be, but I'm confused why there were two options there to begin with...   @robinfhu what's your take?

**Comment by lucaslin** [comment]
Yeah, I'm also confused about why there were two options. 'stack_percent' is never called in the current production code. However, when I tried swapping it for 'expand', the result was exactly the same. 

'expand' uses d3's [chart.offset('expand')](https://github.com/mbostock/d3/wiki/Stack-Layout#offset), but clearly produced an undesirable result, so I made changes to 'stack_percent'.
I think we should just use what is in my changes to 'stack_percent' (and maybe rename it to 'expand'?).

**Comment by liquidpele** [comment]
Well, I'm up for merging this in unless @robinfhu has any objections...

**Comment by liquidpele** [comment]
Went ahead and merged it in, thanks for contributing!

**Pull request merged**
