### PR TITLE
Possible fix for axis not rescaling. 

### PR DESCRIPTION
**Pull request by liquidpele**
https://github.com/novus/nvd3/issues/895

THIS IS NOT COMPLETE.   I'm making this pull request for discussion as a possible solution.  

What this does is it actually makes each chart create a duplicate of each option named the same with an underscore prefix (which is thus hidden in the docs).  Calling the underscore version will be IGNORED if the non-underscore version has been called at some point.  This allows nvd3 to change it's own options internally up until someone changes the option manually from code outside of nvd3.  

Thoughts?

### CODE REVIEW

**Comment by robinfhu** [comment]
Different from my idea, but I like it.  I think this can extend to a lot of options.

**Comment by liquidpele** [comment]
Okay, all the .ticks calls are now ._ticks() so that they can be overridden and the override will keep.

**Comment by robinfhu** [comment]
Thanks. Want to test it out real quick.

**Comment by robinfhu** [comment]
Thanks!!!

**Pull request merged**
