### PR TITLE
Issue 1369: Assigned dispatching events from nv.models.pie to nv.mode…

### PR DESCRIPTION
**Pull request by adnasa**
Addresses the issue described in #1369

### CODE REVIEW

**Comment by liquidpele** [comment]
unit tests failed...  also I'm not sure blindly inheriting all dispatch event is a good idea... I'll need to research that concept some...

**Comment by adnasa** [comment]
@liquidpele 
hmm.. I tested it locally before submitting the patch.

as for the inheritance; the thing here is that slices used in the pieChart model are created in pie.
In some way the *same* instance of the event dispatcher has to be shared between the two.

let me know when you got your "aha!" moment and let's discuss the implementation!

**Comment by liquidpele** [comment]
I mean, as a convenience you could do that, but you can already access them by chart.pie.dispatch too...

**Comment by adnasa** [comment]
I see... oh well.
It took a while to find the dispatching events, so I'm going to go ahead and update the [code example](https://github.com/nvd3-community/nvd3/blob/gh-pages/examples/pieChart.html) and have it there in the mean time for someone else's sake.

**Pull request closed without merging**
