### PR TITLE
Added interpolation for area charts in Multichart type

### PR DESCRIPTION
**Pull request by davizuku**
Fixes issue https://github.com/novus/nvd3/issues/1501

### CODE REVIEW

**Comment by liquidpele** [comment]
pull requests cannot include build files, please remove them from the PR, thanks!

**Comment by davizuku** [comment]
Build files removed from Pull Request, sorry for the inconvenience.

**Comment by davizuku** [comment]
if accepted, will these changes be available using bower?

**Comment by liquidpele** [comment]
Looks good, thanks for contributing.

**Pull request merged**
