### PR TITLE
Do not display "NaN" in tooltip

### PR DESCRIPTION
**Pull request by mgalloue**
- User can customize text displayed for NaN values in a tooltip
- Undefined is displayed by default.

### CODE REVIEW

**Comment by liquidpele** [comment]
Can you explain a little why this is necessary?   It seems odd to want to display undefined values in the tooltip...

**Comment by mgalloue** [comment]
To be consistant with what we see on the chart we can't just hide a dimension with undefined values on the tooltip. The tooltip show all the available dimensions with the corresponding value, taking into account the sorting. Hide this dimension could be misleading the user.

**Comment by mgalloue** [comment]
@liquidpele I don't understand why checks failed, do you know what's happening?

**Comment by liquidpele** [comment]
Travis CI has been fairly unstable for a while now, so you have to go look at the output of the tests to see if it failed or bombed.  In this case, firefox disconnected so the tests didn't actually fail.

**Pull request merged**
