### PR TITLE
remove Controls if showControls=false

### PR DESCRIPTION
**Pull request by mqklin**
I use `nvd3` with `react-nvd3`, and when I update `showControls` prop, controls aren't disappearing. 

I've found all `if (showControls)` lines and added check, that remove `.nv-controlsWrap` if `showContols` is false.

### CODE REVIEW

**Comment by mqklin** [comment]
Hmm... may be it's not `nvd3` concern...

**Comment by topicus** [comment]
@mqklin I think this PR does the job. But It would be great to add the same to the legend component.

**More info:**
- Using showControls directly and calling the update method doesn't change the controls visibility but the object store the control visibility properly.
- Legend component has a similar behavior 
- Other parameters works fine

**Comment by mqklin** [comment]
@topicus @liquidpele I've added fixes with showLegend. Can you review it?

**Comment by mqklin** [comment]
Guys?

**Comment by topicus** [comment]
@mqklin It worked to me. @liquidpele Did you have a chance to review this?

**Comment by liquidpele** [comment]
You're doing .html() on svg elements... some browses (like safari iirc) don't handle that... you probably want to do .selectAll("*").remove();

**Comment by mqklin** [comment]
@liquidpele , I've changed it. Please, check.

**Comment by mqklin** [comment]
fuck... I've deleted it. I'm going to repeat it now

**Pull request closed without merging**
