### PR TITLE
Fix #765

### LINKED ISSUE #765: Tooltip Ghosting issue (introduced in development branch)
An issue must have been introduced when all the tooltip code was changed in: https://github.com/novus/nvd3/commit/5cba3b425c5c

See my screenshot video:
line chart tooltip bug

If you move the mouse kind of fast, it introduces a 'ghost' tooltip that briefly shows up and goes away.  This is happening in the latest Chrome and using nvd3 development.

@liquidpele I'd like to assign this to Drew Peterson, does he have a github account?

### PR DESCRIPTION
**Pull request by petersondrew**
Fix novus/nvd3#765 …

- Reverts nvd3-community/nvd3#51 and nvd3-community/nvd3#42
- Add regression test for novus/nvd3#765

### CODE REVIEW

**Comment by liquidpele** [comment]
Don't check in stuff from the build directory please

**Comment by petersondrew** [comment]
Oh I didn't even notice that, sorry!

**Comment by liquidpele** [comment]
Looks okay to me, everyone else okay with it?

**Comment by robinfhu** [comment]
Let me test it real quick

**Comment by robinfhu** [comment]
Thanks for fixing this so quick!

**Comment by petersondrew** [comment]
No problem, all I really had to do was bring back the code from my original PR nvd3-community/nvd3/pull/8
That explains the fastdom stuff a little more too, in case you were curious about it.

**Pull request merged**
