### PR TITLE
Fix stackedAreaChart yAxis tick format

### PR DESCRIPTION
**Pull request by floribon**
We cannot override yAxis.tickFormat as it keeps a reference to the initial yAxisTickFormat option.

It is not consistent with other charts, such as Line, where it does work.

It also used to work in the old nvd3 live example page: http://nvd3.org/livecode/index.html#codemirrorNav

The code related to the tickFormat on this chart has changed since the newer versions and bring this regression, which this commit fix.

However this erase the use of yAxisTickFormat, which I am not sure if it is obsolete or supported.

Test case without the fix: http://jsfiddle.net/floribon/xu1qz34u/

### CODE REVIEW

**Comment by robinfhu** [comment]
Yes this was an inconsistent option.  I want to check real quick, but your change basically makes 'yAxisTickFormat' a useless option.

**Comment by robinfhu** [comment]
Which I might add, is a good thing because other charts don't have it.

**Comment by robinfhu** [comment]
@floribon can you remove the 'yAxisTickFormat' option from stackedAreaChart, and any references to that variable?

**Comment by liquidpele** [comment]
Agreed, that's a confusing and unnecessary option, best to just nuke it.

**Comment by floribon** [comment]
Ok, done. I wasn't sure if the variable fot introduced by a refactoring and let it open to discussion. Glad we can make it more consistent.

**Comment by liquidpele** [comment]
Oh, you appear to have included stuff under the build directory in your pull request... please remove that.  

https://github.com/novus/nvd3#a-few-rules-for-pull-requests

**Comment by floribon** [comment]
Oops, sorry about that. I'm not super used to pull requests and thought running grunt was a good thing. I should have read this page. Removed.

**Comment by liquidpele** [comment]
Don't forget to change the pull request to go to development and not master too ;)

**Comment by robinfhu** [comment]
I can write a unit test for this.

**Comment by floribon** [comment]
@liquidpele hoe can I do that? Should I create a new pull request from the development branch, and somehow remove this one? Or is there a way to redirect the pull request?

**Comment by robinfhu** [comment]
@floribon I'll take care of it.  I am going to merge this in with a unit test to the development branch in a few minutes.

**Comment by robinfhu** [comment]
Merged to development. Thanks @floribon

**Comment by robinfhu** [comment]
Hmm, just realized that this introduced another bug.  I'll fix it and PR it :-)

**Comment by robinfhu** [comment]
@floribon @liquidpele @portante see pull request #795 for a follow-up fix.

**Comment by floribon** [comment]
Awesome, thanks for all of this @robinfhu. I was very pleased to see nvd3 back on track, keep up the excellent work!

**Pull request closed without merging**
