### PR TITLE
Not to overwrite top margin & availableHeight depending on a legend's height

### PR DESCRIPTION
**Pull request by ovvn**
Fix for #1585

### CODE REVIEW

**Comment by liquidpele** [comment]
I don't understand why this is a fix... does this not make the chart and the legend overlap?

**Comment by ovvn** [comment]
There're two approaches
1. Not to overwrite the top margin & availableHeight depending on a legend's height. In this case user has a full control over the look of the chart. So he can set a top margin in a way that will prevent the chart and legend from overlapping.
2. Overwrite the top margin & availableHeight only in case the legend's height is bigger than the top margin. In this case user's specified top margin will be overwritten when the legend's height is bigger than the margin in order to prevent the overlapping.

I made two pull request for each of the case respectively.

**Comment by liquidpele** [comment]
I think this is fixed by https://github.com/novus/nvd3/pull/1808 please confirm.

**Comment by ovvn** [comment]
I don't think the PR #1808 is a right thing to do as it's actually rolls back this PR https://github.com/novus/nvd3/pull/1642
and bring us back to the situation where setting a top margin doesn't work at all https://github.com/novus/nvd3/issues/1585

**Comment by liquidpele** [comment]
Yea, it does roll it back, but the original PR caused an issue.   We really need to check if the margin was overridden or not and only have it adjust if it wasn't specifically set.

**Comment by ovvn** [comment]
That's right, but now we adjust a top margin anytime it's different from legend, i.e. overwrite it with the legend's height. That's why no top margin can be specified at all.

**Comment by ovvn** [comment]
> We really need to check if the margin was overridden or not and only have it adjust if it wasn't specifically set.

Created a PR #1821 which implements the concept.

**Pull request closed without merging**
