### PR TITLE
Issue #963 Prevent a null point from being highlighted in lineChart

### PR DESCRIPTION
**Pull request by robinfhu**
In example, show N/A in the tooltip if value undefined

### CODE REVIEW

**Comment by LeeMendelowitz** [comment]
This isn't working for my test case - I think this picks points with different X values from different series.

**Comment by LeeMendelowitz** [comment]
@robinfhu it picks the closest defined X for each series, and highlights the point, and shows in the tooltip.  This isn't right because the tooltip also displays an X value which doesn't match the highlighted points.

**Comment by LeeMendelowitz** [comment]
robin_fix

**Comment by robinfhu** [comment]
@LeeMendelowitz , ok.  I am starting to understand why this is a problem for your use case.

First, you are creating data points where X=null, which you should not be doing.  This will break the chart in many ways.  Can you not preprocess your data to prevent nulls in your X values?

**Comment by LeeMendelowitz** [comment]
@robinfhu Okay, I'll fix the test case so x is never null and check it out.

**Comment by LeeMendelowitz** [comment]
964_not_null

@robinfhu here's with not null. Now the point isn't highlighted but still appears in tooltip. Issue is that `chart.y()` converts the null to a 0.0 before your fix checks for null.

**Comment by robinfhu** [comment]
@LeeMendelowitz  is there a way you can augment my solution?

**Comment by LeeMendelowitz** [comment]
@robinfhu Sure, I'll check it out and make a PR to your repo?

**Comment by robinfhu** [comment]
@LeeMendelowitz  sure

**Comment by LeeMendelowitz** [comment]
@robinfhu see https://github.com/novus/nvd3/pull/965

**Pull request closed without merging**
