### PR TITLE
Fixed bug where bar charts show bars for 0 and null values

### PR DESCRIPTION
**Pull request by sezgi**
Here's a jsfiddle showing the bug:
https://jsfiddle.net/sezgi/xg1b2zz2/

### CODE REVIEW

**Comment by smills2929** [comment]
It should show bars for 0 values, however it should not for null values.

**Comment by liquidpele** [comment]
IIRC the novus guys did that on purpose so that you could see a tiny bit of the chart, otherwise it looked like it was just missing.

**Comment by smills2929** [comment]
I think null values should not show, but it makes sense to show 0 values.
To me null should be interpreted as missing.
On 27 Apr 2016 06:36, "liquidpele" <notifications@github.com> wrote:

IIRC the novus guys did that on purpose so that you could see a tiny bit of
the chart, otherwise it looked like it was just missing.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/novus/nvd3/pull/1550#issuecomment-214908325>

**Comment by liquidpele** [comment]
You say it makes sense to show 0 values... but if you have a height of zero then it's effectively not shown...

**Pull request closed without merging**
