### PR TITLE
Extended object attribute access for Box Plot model.

### PR DESCRIPTION
**Pull request by jjzazuet**
- Extending Box Plot model to support attribute accessor callbacks for custom models.
- Model remains backwards compatible with original data structure implementation (e.g. `label, values, outliers`, etc.). `y` chart option now emits a deprecation warning to the developer.
- Adding support for outlier elements as objects including label, color and value.
- Updated Box plot test case page.
- Cleaned up JSHint linter warnings for Box plot model.
- Updated examples page with existing and new example entry.

### CODE REVIEW

**Comment by billderose** [comment]
there are some changes in here I'd like to see as well. @jjzazuet, is it possible to include in this change the ability for user defined ticks. [This line](https://github.com/novus/nvd3/pull/1395/files#diff-1324737ebf62c585c9b05589372c802fR143) always uses the height to determine the number of ticks but it seems like we could add that option here.

**Comment by jjzazuet** [comment]
@billderose ok so let me see if I understood correctly. Instead of determining the tick size with a fixed value:

    .ticks( Math.floor(availableHeight/36) )

We could instead say:

    .ticks( Math.floor(availableHeight/someCustomTickSizeOrDefaultToFixedValue) )

Is this about right? Thanks!

**Comment by billderose** [comment]
@jjzazuet that's along the right lines. I'm wondering if it would be best to do something like `ticks(customTicks)` which would allow any number of ticks and would not require the user to guess and check their `customTicks` value. We can always fallback to the `.ticks( Math.floor(availableHeight/36) )` in the absence of a used defined value.

**Comment by jjzazuet** [comment]
@liquidpele , any chances of merging this one before I try further changes? Thanks for your time and help!

**Comment by liquidpele** [comment]
Oh wow, that's a lot of change...  @Turgar you want to take a look at this since you were the original boxplot contributor?

**Comment by Turgar** [comment]
@liquidpele New code LGTM -- I'll try it out soon. Thanks!

**Comment by Turgar** [comment]
@liquidpele No objections here if you want to merge.

**Comment by liquidpele** [comment]
Cool, merging in then.

**Comment by jjzazuet** [comment]
@liquidpele @Turgar Thanks! ;)

**Pull request merged**
