### PR TITLE
Enhancement - More modular implementation of focus charts.

### PR DESCRIPTION
**Pull request by Snuggert**
Used the focus chart base from the lineChart model and adapted the code so the StackedAreaChart model could focus as well.

Should probably include some unit-testing in the future.

### CODE REVIEW

**Comment by liquidpele** [comment]
Oh wow, this is cool.... looks like you have a conflict with master though, you need to merge in upstream master and fix the conflict in your branch.

**Comment by Snuggert** [comment]
I merged my branch with the current master.

**Comment by liquidpele** [comment]
wtf... github is showing stuff in your PR that is already merged to master now.   

Guess I'll wait and see if it fixes itself...

**Comment by Snuggert** [comment]
Could it be that I broke everything in my attempt to merge with upstream?

**Comment by liquidpele** [comment]
Not sure... I mean, I merged in other PRs yesterday, and I see those in your changeset, so I'm confused why github would show them here since the diff with master shouldn't show them.  Something weird like this happened a while back and I contacted github support and it fixed itself magically before they responded (of course) so I dunno. 

Is this the process you used?  If not, this is the proper way:

1. First create the upstream:     https://help.github.com/articles/configuring-a-remote-for-a-fork/ 
2. Then merge latest upstream into your branch:    https://help.github.com/articles/syncing-a-fork/

**Comment by Snuggert** [comment]
Yup. That's the guide I used.

**Comment by Snuggert** [comment]
I think I unfucked everything. :)

**Comment by liquidpele** [comment]
Ah, that looks better!   

I'll grab this and test it a bit first when I get a chance since it's kind of core functionality, but I'd love to break out focus to be reusable like this!

**Pull request merged**
